package org.matrix.vector.manager.data.github

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * The slice of GitHub's commit payload the Home feed needs.
 *
 * One request to `/commits?since=…` carries everything: the author's login and avatar for the
 * contributor row, the date for the timeline, the subject line, and the SHA. There is deliberately
 * no second call to `/contributors` — the people are derived from the commits, which both halves
 * the rate-limit spend and makes the row mean "who worked on this *recently*" rather than an
 * all-time leaderboard nobody reads twice.
 */
@Serializable
data class GhCommit(
    val sha: String,
    val commit: GhCommitDetail,
    val author: GhUser? = null,
    @SerialName("html_url") val htmlUrl: String? = null,
)

@Serializable data class GhCommitDetail(val message: String, val author: GhCommitAuthor)

@Serializable
data class GhCommitAuthor(
    val name: String,
    val date: String,
    /** Present on every commit, and the only handle on an author GitHub failed to link. */
    val email: String = "",
)

@Serializable
data class GhUser(
    val login: String,
    @SerialName("avatar_url") val avatarUrl: String? = null,
    @SerialName("html_url") val htmlUrl: String? = null,
    val type: String? = null,
)

@Serializable
data class GhRepo(
    @SerialName("stargazers_count") val stars: Int = 0,
    @SerialName("forks_count") val forks: Int = 0,
    @SerialName("open_issues_count") val openIssues: Int = 0,
    val license: GhLicense? = null,
)

@Serializable data class GhLicense(@SerialName("spdx_id") val spdxId: String? = null)

/** How a commit subject is classified. Vector writes plain imperative subjects, not
 * conventional-commit prefixes, so the leading verb is what gets read. Validated over the last 300
 * commits: `Fix` 56, `Bump`/`Update`/`Upgrade` 88, `Add`/`New`/`Implement` 22, `Remove`/`Delete`
 * 14. */
enum class CommitKind {
    Fix,
    Add,
    Remove,
    Chore,
    Change;

    companion object {
        fun of(subject: String): CommitKind =
            when (subject.substringBefore(' ').trimStart('[').lowercase()) {
                "fix",
                "fixes",
                "fixed" -> Fix
                "add",
                "adds",
                "new",
                "implement",
                "introduce",
                "allow",
                "support" -> Add
                "remove",
                "removes",
                "delete",
                "drop" -> Remove
                "bump",
                "update",
                "upgrade",
                "migrate",
                "translation]",
                "translation" -> Chore
                else -> Change
            }
    }
}

/**
 * One person credited on a commit — the author, or anyone named in a `Co-authored-by:` trailer.
 *
 * Co-authors are real contributors and are counted as such. GitHub's commits API does not return
 * them as users, so they are parsed out of the message; when the trailer carries a GitHub noreply
 * address the login and avatar can be recovered from it exactly, and otherwise the person is shown
 * under the name they signed with and a monogram.
 */
data class CommitPerson(
    val login: String,
    val avatarUrl: String?,
    val profileUrl: String?,
    val isBot: Boolean = false,
)

/** A commit as the timeline renders it. */
data class TimelineCommit(
    val sha: String,
    val shortSha: String,
    val subject: String,
    val kind: CommitKind,
    /** Pull-request number parsed from a trailing `(#123)`, the link to the discussion. */
    val pullRequest: Int?,
    /** The author first, then any co-authors, deduplicated. */
    val authors: List<CommitPerson>,
    val epochSeconds: Long,
    val htmlUrl: String?,
    /**
     * Distance from the repository's first commit, i.e. this commit's own version number —
     * `versionCode` is generated by `git rev-list --count`, so the two are the same scale and a
     * build can be located on the timeline exactly.
     */
    val globalIndex: Long,
    /** True when anyone credited is not the repository owner — highlighted on the rail. */
    val isCommunity: Boolean,
    val isBot: Boolean,
) {
    val authorLogin: String
        get() = authors.firstOrNull()?.login.orEmpty()

    val coAuthors: List<CommitPerson>
        get() = authors.drop(1)
}

/** A person credited inside the window, with how much and how recently. */
data class Contributor(
    val login: String,
    val avatarUrl: String?,
    val profileUrl: String?,
    val commits: Int,
    /** Their most recent commit in the window; breaks ties so the row stays a live scoreboard. */
    val lastEpochSeconds: Long,
)

/** Everything the Home community section renders, or the reason it cannot. */
data class CommunityFeed(
    val commits: List<TimelineCommit> = emptyList(),
    val contributors: List<Contributor> = emptyList(),
    val windowStartEpochSeconds: Long = 0,
    val repo: GhRepo? = null,
    /** Commits on the default branch, ever. Equals the newest build's versionCode. */
    val totalCommits: Long = 0,
    /** True when this came off disk rather than the network. */
    /** True when this came off disk rather than the network, for any reason. */
    val fromCache: Boolean = false,
    /**
     * True only when the network was actually tried and could not be reached.
     *
     * Not the same as [fromCache]. Home deliberately reads the cache on most launches, so telling
     * the user "could not reach GitHub" whenever the feed came from disk announced a failure that
     * had not happened — the app simply had not asked.
     */
    val offline: Boolean = false,
    /**
     * False until the first load resolves. Without it the initial empty value is indistinguishable
     * from a genuinely empty result, and the page claims "no commits" before it has looked.
     */
    val loaded: Boolean = false,
) {
    val commitCount: Int
        get() = commits.size

    val isEmpty: Boolean
        get() = commits.isEmpty()
}

// --- CI builds ------------------------------------------------------------------------------

@Serializable
data class GhRelease(
    val id: Long,
    @SerialName("tag_name") val tagName: String = "",
    val name: String? = null,
    val prerelease: Boolean = false,
    @SerialName("target_commitish") val targetCommitish: String = "",
    @SerialName("published_at") val publishedAt: String? = null,
    @SerialName("html_url") val htmlUrl: String? = null,
    val body: String? = null,
    val assets: List<GhReleaseAsset> = emptyList(),
)

@Serializable
data class GhReleaseAsset(
    val id: Long,
    val name: String,
    val size: Long = 0,
    @SerialName("browser_download_url") val downloadUrl: String? = null,
)

@Serializable
data class GhWorkflowRuns(
    @SerialName("workflow_runs") val runs: List<GhWorkflowRun> = emptyList()
)

@Serializable
data class GhWorkflowRun(
    val id: Long,
    val name: String? = null,
    @SerialName("head_branch") val headBranch: String? = null,
    @SerialName("head_sha") val headSha: String = "",
    @SerialName("display_title") val displayTitle: String? = null,
    @SerialName("created_at") val createdAt: String = "",
    @SerialName("html_url") val htmlUrl: String? = null,
    val conclusion: String? = null,
)

@Serializable
data class GhArtifacts(val artifacts: List<GhArtifact> = emptyList())

@Serializable
data class GhArtifact(
    val id: Long,
    val name: String,
    @SerialName("size_in_bytes") val sizeInBytes: Long = 0,
    val expired: Boolean = false,
    @SerialName("archive_download_url") val downloadUrl: String? = null,
)

/** A successful CI run, as the canary screen renders it. */
data class CanaryBuild(
    val id: Long,
    val title: String,
    val branch: String,
    val shortSha: String,
    val epochSeconds: Long,
    val htmlUrl: String?,
    val artifacts: List<CanaryArtifact>,
)

/**
 * A published build of the framework, canary or stable, with the zip to flash.
 *
 * One type for both channels because the install path is identical — the difference is only which
 * of them a given reader is allowed to be offered.
 */
data class FrameworkRelease(
    val tag: String,
    val title: String,
    val versionCode: Long,
    val isCanary: Boolean,
    val notesMarkdown: String?,
    val htmlUrl: String?,
    val epochSeconds: Long,
    /**
     * The commit the release was cut from, when GitHub knows one.
     *
     * `target_commitish` is a full SHA for the canaries, because CI creates them against an exact
     * commit — but it is the literal string "master" for a hand-made release, which names a branch
     * and not a build. Only the first kind can be compared against, and the difference between
     * "these differ" and "I cannot tell" is one the UI has to keep.
     */
    val commit: String?,
    /**
     * Every zip the release published, in the order GitHub listed them.
     *
     * A list rather than the single "first zip" this used to keep: each release ships a Release
     * and a Debug build, 8 MB against 22 MB, and picking whichever GitHub happened to list first
     * meant the reader could neither choose nor tell which one they were about to flash. The app
     * asks people for a debug build when they report a problem, so it has to be able to install
     * one.
     */
    val zips: List<CanaryArtifact>,
) {
    /** The one to offer by default when nothing has been chosen. */
    val defaultZip: CanaryArtifact?
        get() = zips.firstOrNull { it.variant == ZipVariant.Release } ?: zips.firstOrNull()
}

/**
 * Which build a zip is, read from its file name.
 *
 * [Other] is not a failure: a release may one day publish something these two names do not cover,
 * and a picker that cannot represent it would either hide the file or mislabel it. Both are worse
 * than showing the name it actually has.
 */
enum class ZipVariant(val key: String) {
    Release("release"),
    Debug("debug"),
    Other("other"),
}

data class CanaryArtifact(
    val id: Long,
    val name: String,
    val sizeInBytes: Long,
    val expired: Boolean,
    val downloadUrl: String?,
) {
    val variant: ZipVariant
        get() =
            when {
                name.contains("release", ignoreCase = true) -> ZipVariant.Release
                name.contains("debug", ignoreCase = true) -> ZipVariant.Debug
                else -> ZipVariant.Other
            }
}

